### ISSUE TITLE
Guess its rating

### ISSUE THREAD

**Issue by tissatussa** [dannyhammer/toad#93]
Last few days i let Toad play several (mostly) 5m+3s games against other engines about the same strength. Here's the list : [Toad-games.zip](https://github.com/user-attachments/files/17876432/Toad-games.zip)

![Toad-game-results](https://github.com/user-attachments/assets/d3848bd7-325b-4863-814b-c51637449c88)

I used several Toad versions, but mostly the latest v2.0.0. A few games had a custom starting position. Ratings are from the latest CCRL lists - some engines are not mentioned there, i gave my estimate. I guess its rating is about 2300.

**Comment by dannyhammer** [comment]
Thank you so much for providing this info!

**Comment by tissatussa** [comment]
@dannyhammer due to your README i discovered the engine Yukari, which is about equal strength. Thanks. I'm closing this Issue now.
